SELECT
    ANIMAL_INS.ANIMAL_ID,
    ANIMAL_INS.ANIMAL_TYPE,
    ANIMAL_INS.NAME
FROM
    ANIMAL_INS,
    ANIMAL_OUTS
where
    ANIMAL_INS.ANIMAL_ID = ANIMAL_OUTS.ANIMAL_ID
and
    ANIMAL_INS.SEX_UPON_INTAKE like 'Intact%'
and
    ANIMAL_OUTS.SEX_UPON_OUTCOME not like 'Intact%'
order by ANIMAL_INS.ANIMAL_ID asc;