SELECT
    TO_CHAR(DATETIME, 'HH24') HOUR,
    count(TO_CHAR(DATETIME, 'HH24')) count
FROM
    ANIMAL_OUTS
GROUP BY TO_CHAR(DATETIME, 'HH24')
HAVING TO_CHAR(DATETIME, 'HH24') > 8
and TO_CHAR(DATETIME, 'HH24') < 20
ORDER BY TO_CHAR(DATETIME, 'HH24') asc;