SELECT INFO.FOOD_TYPE, INFO.REST_ID, INFO.REST_NAME, INFO.FAVORITES
    FROM REST_INFO AS INFO
        INNER JOIN (
            SELECT FOOD_TYPE, MAX(FAVORITES) AS _MAX
                FROM REST_INFO
                GROUP BY FOOD_TYPE) AS FAVORITES_INFO
        ON INFO.FOOD_TYPE = FAVORITES_INFO.FOOD_TYPE
    WHERE INFO.FAVORITES = FAVORITES_INFO._MAX
    ORDER BY INFO.FOOD_TYPE DESC